# Generated by Django 5.1.7 on 2025-05-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
